steps:
# build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gdg-cloud-run/cloud-run-hello-api:$COMMIT_SHA', '.']
# push docker image to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gdg-cloud-run/cloud-run-hello-api:$COMMIT_SHA']
# deploy app on cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run' , 'deploy', 'cloud-run-hello-api', '--platform', 'managed', '--region', 'australia-southeast1', '--image', 'gcr.io/gdg-cloud-run/cloud-run-hello-api:$COMMIT_SHA', '--service-account', 'cloud-run-hello-api', '--no-allow-unauthenticated']
